# Generated by Django 4.1.2 on 2022-10-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="owner",
            new_name="dono",
        ),
        migrations.RenameField(
            model_name="store",
            old_name="name",
            new_name="nome",
        ),
    ]
